In [49]:
import pandas as pd

# Level 1

In [2]:
import pandas as pd

data = {
    "Name":["Arun","Bala","Charan","Divya","Esha"],
    "Age":[21,22,20,23,21],
    "Department":["IT","HR","IT","Sales","HR"],
    "Salary":[45000,35000,50000,42000,37000]
}

df = pd.DataFrame(data)

In [3]:
#Display the first 3 rows.

df.head(3)

     Name  Age Department  Salary
0    Arun   21         IT   45000
1    Bala   22         HR   35000
2  Charan   20         IT   50000

In [5]:
#Display the last 2 rows.
df.tail(2)

    Name  Age Department  Salary
3  Divya   23      Sales   42000
4   Esha   21         HR   37000

In [6]:
#Print only the Name column.
df["Name"]

0      Arun
1      Bala
2    Charan
3     Divya
4      Esha
Name: Name, dtype: str

In [12]:
#Print Name and Salary.

df[["Name","Salary"]]

     Name  Salary
0    Arun   45000
1    Bala   35000
2  Charan   50000
3   Divya   42000
4    Esha   37000

In [17]:
#Find the shape of the dataframe.

df.shape

(5, 4)

In [20]:
#Display column names.

df.columns

Index(['Name', 'Age', 'Department', 'Salary'], dtype='str')

In [25]:
#Find the data type of every column.

df.dtypes

Name            str
Age           int64
Department      str
Salary        int64
dtype: object

In [27]:
#Print all employees whose salary is greater than 40000.

df[df["Salary"] > 40000]

     Name  Age Department  Salary
0    Arun   21         IT   45000
2  Charan   20         IT   50000
3   Divya   23      Sales   42000

In [28]:
#Print employees from the IT department.

df[df["Department"] == "IT"]

     Name  Age Department  Salary
0    Arun   21         IT   45000
2  Charan   20         IT   50000

In [37]:
#Find the average salary.

df["Salary"].mean() #41800.00
int(df["Salary"].mean())

41800

# Level 2

In [39]:
#Employees whose age is greater than 21.

df[df["Age"] > 21]

    Name  Age Department  Salary
1   Bala   22         HR   35000
3  Divya   23      Sales   42000

In [41]:
#Employees whose department is HR.

df[df["Department"] == "HR"]

   Name  Age Department  Salary
1  Bala   22         HR   35000
4  Esha   21         HR   37000

In [44]:
#Employees with salary between 35000 and 45000.

df[(df["Salary"] > 35000) & (df["Salary"] < 45000)]

    Name  Age Department  Salary
3  Divya   23      Sales   42000
4   Esha   21         HR   37000

In [45]:
#Employees whose department is IT and salary > 45000.

df[(df["Department"]=="IT") & (df["Salary"] > 45000)]

     Name  Age Department  Salary
2  Charan   20         IT   50000

In [47]:
#Employees whose department is HR or Sales.

df[(df["Department"] == "HR") | (df["Department"] == "Sales")]

    Name  Age Department  Salary
1   Bala   22         HR   35000
3  Divya   23      Sales   42000
4   Esha   21         HR   37000

In [53]:
#Employees whose name starts with "A".

df[df["Name"].str.startswith("A")]

   Name  Age Department  Salary
0  Arun   21         IT   45000

In [55]:
#Employees whose name ends with "a".

df[df["Name"].str.startswith("a")]

Empty DataFrame
Columns: [Name, Age, Department, Salary]
Index: []

In [56]:
#Employees whose age is 21 or 23.

df[(df["Age"] == 21) | (df["Age"] == 23)]

    Name  Age Department  Salary
0   Arun   21         IT   45000
3  Divya   23      Sales   42000
4   Esha   21         HR   37000

In [57]:
#Find employees whose salary is not equal to 42000.

df[df["Salary"] != 42000]

     Name  Age Department  Salary
0    Arun   21         IT   45000
1    Bala   22         HR   35000
2  Charan   20         IT   50000
4    Esha   21         HR   37000

In [63]:
#Sort employees by salary in ascending order.

df.sort_values("Salary",ascending=False)

     Name  Age Department  Salary
2  Charan   20         IT   50000
0    Arun   21         IT   45000
3   Divya   23      Sales   42000
4    Esha   21         HR   37000
1    Bala   22         HR   35000

# Level 3

In [64]:
#Find maximum salary.

max(df["Salary"])

50000

In [66]:
#Find minimum salary.

min(df["Salary"])

35000

In [72]:
#Find median salary.

df["Salary"].median()

np.float64(42000.0)

In [73]:
#Find standard deviation of salary.

df["Salary"].std()

np.float64(6058.052492344384)

In [78]:
#Count total employees

df["Name"].count()
df["Name"].nunique()

5

In [85]:
#Count employees in each department.

df["Department"].value_counts()

Department
IT       2
HR       2
Sales    1
Name: count, dtype: int64

In [90]:
#Find total salary paid.

df["Salary"].sum()

np.int64(209000)

In [92]:
#Find average age.

int(df["Age"].mean())

21

In [106]:
#Find the employee with highest salary.

df.nsmallest(1,"Salary")
df.nsmallest(2, "Salary").tail(1)
#df.loc[df["Salary"].idxmax()]

   Name  Age Department  Salary
4  Esha   21         HR   37000

In [102]:
#Find the employee with lowest salary.

df.loc[df["Salary"].idxmin()]

Name           Bala
Age              22
Department       HR
Salary        35000
Name: 1, dtype: object