In [1]:
import pandas as pd

In [2]:
import pandas as pd

data = {
    "Name":["Arun","Bala","Charan","Divya","Esha"],
    "Age":[21,22,20,23,21],
    "Department":["IT","HR","IT","Sales","HR"],
    "Salary":[45000,35000,50000,42000,37000]
}

df = pd.DataFrame(data)

In [3]:
#Display the first 3 rows.

df.head(3)

     Name  Age Department  Salary
0    Arun   21         IT   45000
1    Bala   22         HR   35000
2  Charan   20         IT   50000

In [5]:
#Display the last 2 rows.
df.tail(2)

    Name  Age Department  Salary
3  Divya   23      Sales   42000
4   Esha   21         HR   37000

In [6]:
#Print only the Name column.
df["Name"]

0      Arun
1      Bala
2    Charan
3     Divya
4      Esha
Name: Name, dtype: str

In [12]:
#Print Name and Salary.

df[["Name","Salary"]]

     Name  Salary
0    Arun   45000
1    Bala   35000
2  Charan   50000
3   Divya   42000
4    Esha   37000

In [17]:
#Find the shape of the dataframe.

df.shape

(5, 4)

In [20]:
#Display column names.

df.columns

Index(['Name', 'Age', 'Department', 'Salary'], dtype='str')

In [25]:
#Find the data type of every column.

df.dtypes

Name            str
Age           int64
Department      str
Salary        int64
dtype: object

In [27]:
#Print all employees whose salary is greater than 40000.

df[df["Salary"] > 40000]

     Name  Age Department  Salary
0    Arun   21         IT   45000
2  Charan   20         IT   50000
3   Divya   23      Sales   42000

In [28]:
#Print employees from the IT department.

df[df["Department"] == "IT"]

     Name  Age Department  Salary
0    Arun   21         IT   45000
2  Charan   20         IT   50000

In [37]:
#Find the average salary.

df["Salary"].mean() #41800.00
int(df["Salary"].mean())

41800