In [123]:
import pandas as pd

# Level 1 (Basics)

In [80]:
import pandas as pd

data = {
    "Name":["Arun","Bala","Charan","Divya","Esha"],
    "Age":[21,22,20,23,21],
    "Department":["IT","HR","IT","Sales","HR"],
    "Salary":[45000,35000,50000,42000,37000]
}

df = pd.DataFrame(data)

In [3]:
#Display the first 3 rows.

df.head(3)

     Name  Age Department  Salary
0    Arun   21         IT   45000
1    Bala   22         HR   35000
2  Charan   20         IT   50000

In [5]:
#Display the last 2 rows.
df.tail(2)

    Name  Age Department  Salary
3  Divya   23      Sales   42000
4   Esha   21         HR   37000

In [6]:
#Print only the Name column.
df["Name"]

0      Arun
1      Bala
2    Charan
3     Divya
4      Esha
Name: Name, dtype: str

In [12]:
#Print Name and Salary.

df[["Name","Salary"]]

     Name  Salary
0    Arun   45000
1    Bala   35000
2  Charan   50000
3   Divya   42000
4    Esha   37000

In [17]:
#Find the shape of the dataframe.

df.shape

(5, 4)

In [20]:
#Display column names.

df.columns

Index(['Name', 'Age', 'Department', 'Salary'], dtype='str')

In [25]:
#Find the data type of every column.

df.dtypes

Name            str
Age           int64
Department      str
Salary        int64
dtype: object

In [27]:
#Print all employees whose salary is greater than 40000.

df[df["Salary"] > 40000]

     Name  Age Department  Salary
0    Arun   21         IT   45000
2  Charan   20         IT   50000
3   Divya   23      Sales   42000

In [28]:
#Print employees from the IT department.

df[df["Department"] == "IT"]

     Name  Age Department  Salary
0    Arun   21         IT   45000
2  Charan   20         IT   50000

In [37]:
#Find the average salary.

df["Salary"].mean() #41800.00
int(df["Salary"].mean())

41800

# Level 2 (Filtering)

In [39]:
#Employees whose age is greater than 21.

df[df["Age"] > 21]

    Name  Age Department  Salary
1   Bala   22         HR   35000
3  Divya   23      Sales   42000

In [41]:
#Employees whose department is HR.

df[df["Department"] == "HR"]

   Name  Age Department  Salary
1  Bala   22         HR   35000
4  Esha   21         HR   37000

In [44]:
#Employees with salary between 35000 and 45000.

df[(df["Salary"] > 35000) & (df["Salary"] < 45000)]

    Name  Age Department  Salary
3  Divya   23      Sales   42000
4   Esha   21         HR   37000

In [45]:
#Employees whose department is IT and salary > 45000.

df[(df["Department"]=="IT") & (df["Salary"] > 45000)]

     Name  Age Department  Salary
2  Charan   20         IT   50000

In [47]:
#Employees whose department is HR or Sales.

df[(df["Department"] == "HR") | (df["Department"] == "Sales")]

    Name  Age Department  Salary
1   Bala   22         HR   35000
3  Divya   23      Sales   42000
4   Esha   21         HR   37000

In [53]:
#Employees whose name starts with "A".

df[df["Name"].str.startswith("A")]

   Name  Age Department  Salary
0  Arun   21         IT   45000

In [55]:
#Employees whose name ends with "a".

df[df["Name"].str.startswith("a")]

Empty DataFrame
Columns: [Name, Age, Department, Salary]
Index: []

In [56]:
#Employees whose age is 21 or 23.

df[(df["Age"] == 21) | (df["Age"] == 23)]

    Name  Age Department  Salary
0   Arun   21         IT   45000
3  Divya   23      Sales   42000
4   Esha   21         HR   37000

In [57]:
#Find employees whose salary is not equal to 42000.

df[df["Salary"] != 42000]

     Name  Age Department  Salary
0    Arun   21         IT   45000
1    Bala   22         HR   35000
2  Charan   20         IT   50000
4    Esha   21         HR   37000

In [63]:
#Sort employees by salary in ascending order.

df.sort_values("Salary",ascending=False)

     Name  Age Department  Salary
2  Charan   20         IT   50000
0    Arun   21         IT   45000
3   Divya   23      Sales   42000
4    Esha   21         HR   37000
1    Bala   22         HR   35000

# Level 3 (Statistics)

In [64]:
#Find maximum salary.

max(df["Salary"])

50000

In [66]:
#Find minimum salary.

min(df["Salary"])

35000

In [72]:
#Find median salary.

df["Salary"].median()

np.float64(42000.0)

In [73]:
#Find standard deviation of salary.

df["Salary"].std()

np.float64(6058.052492344384)

In [78]:
#Count total employees

df["Name"].count()
df["Name"].nunique()

5

In [85]:
#Count employees in each department.

df["Department"].value_counts()

Department
IT       2
HR       2
Sales    1
Name: count, dtype: int64

In [90]:
#Find total salary paid.

df["Salary"].sum()

np.int64(209000)

In [92]:
#Find average age.

int(df["Age"].mean())

21

In [106]:
#Find the employee with highest salary.

df.nsmallest(1,"Salary")
df.nsmallest(2, "Salary").tail(1)
#df.loc[df["Salary"].idxmax()]

   Name  Age Department  Salary
4  Esha   21         HR   37000

In [102]:
#Find the employee with lowest salary.

df.loc[df["Salary"].idxmin()]

Name           Bala
Age              22
Department       HR
Salary        35000
Name: 1, dtype: object

# Level 4 (GroupBy)

In [110]:
#Find average salary department-wise.

df.groupby("Department")["Salary"].mean()

Department
HR       36000.0
IT       47500.0
Sales    42000.0
Name: Salary, dtype: float64

In [11]:
#Find maximum salary department-wise.

df.groupby("Department")["Salary"].max()

Department
HR       37000
IT       50000
Sales    42000
Name: Salary, dtype: int64

In [18]:
#Count employees department-wise.

df.groupby("Department")["Department"].count()

Department
HR       2
IT       2
Sales    1
Name: Department, dtype: int64

In [21]:
#Find total salary department-wise.

df.groupby("Department")["Salary"].sum()

Department
HR       72000
IT       95000
Sales    42000
Name: Salary, dtype: int64

In [24]:
#Find minimum age department-wise.

df.groupby("Department")["Age"].min()

Department
HR       21
IT       20
Sales    23
Name: Age, dtype: int64

In [25]:
#Find average age department-wise.

df.groupby("Department")["Age"].mean()

Department
HR       21.5
IT       20.5
Sales    23.0
Name: Age, dtype: float64

In [30]:
#Find department having highest average salary.

df.groupby("Department")["Salary"].mean().idxmax()

'IT'

In [33]:
#Find department with maximum employees.

df.groupby("Department")["Salary"].count().idxmax()

'HR'

In [13]:
#Find total employees and average salary together.

df.agg({"Name": "nunique", "Salary": "mean"})

Name          5.0
Salary    41800.0
dtype: float64

In [24]:
#Use agg() to calculate

#mean
#max
#min

#salary department-wise.

df.groupby("Department")["Salary"].agg(["mean", "mean", "min"])

               mean     mean    min
Department
HR          36000.0  36000.0  35000
IT          47500.0  47500.0  45000
Sales       42000.0  42000.0  42000

# Level 5 (Sorting & Indexing)

In [29]:
#Sort salary descending.

df.sort_values("Salary",ascending=False)

     Name  Age Department  Salary
2  Charan   20         IT   50000
0    Arun   21         IT   45000
3   Divya   23      Sales   42000
4    Esha   21         HR   37000
1    Bala   22         HR   35000

In [43]:
#Sort by Department then Salary.

df.sort_values(by=["Department","Salary"])
df.sort_values(by=["Department","Salary"],ascending=[True,False])

     Name  Age Department  Salary
4    Esha   21         HR   37000
1    Bala   22         HR   35000
2  Charan   20         IT   50000
0    Arun   21         IT   45000
3   Divya   23      Sales   42000

In [45]:
#Reset index after sorting.

df.sort_values(by=["Department","Salary"],ascending=[True,False],).reset_index(drop=True)

     Name  Age Department  Salary
0    Esha   21         HR   37000
1    Bala   22         HR   35000
2  Charan   20         IT   50000
3    Arun   21         IT   45000
4   Divya   23      Sales   42000

In [59]:
#Set Name as index.

df.sort_values(by=["Department","Salary"],ascending=True).set_index("Name").loc["Divya"]

Age              23
Department    Sales
Salary        42000
Name: Divya, dtype: object

In [62]:
#Access first three rows using .iloc.

df.iloc[:3]

     Name  Age Department  Salary
0    Arun   21         IT   45000
1    Bala   22         HR   35000
2  Charan   20         IT   50000

In [69]:
#Access rows 2–4 and columns Name & Salary using .iloc.

df.iloc[2:5,[0,3]]

     Name  Salary
2  Charan   50000
3   Divya   42000
4    Esha   37000

In [81]:
#Rename Salary to MonthlySalary.

df.rename(columns={"Salary":"MonthlySalary"}) #inplace=True

     Name  Age Department  MonthlySalary
0    Arun   21         IT          45000
1    Bala   22         HR          35000
2  Charan   20         IT          50000
3   Divya   23      Sales          42000
4    Esha   21         HR          37000

In [82]:
df

     Name  Age Department  Salary
0    Arun   21         IT   45000
1    Bala   22         HR   35000
2  Charan   20         IT   50000
3   Divya   23      Sales   42000
4    Esha   21         HR   37000

In [84]:
#Drop the Age column.

df.drop(columns={"Age"})

     Name Department  Salary
0    Arun         IT   45000
1    Bala         HR   35000
2  Charan         IT   50000
3   Divya      Sales   42000
4    Esha         HR   37000

In [85]:
df

     Name  Age Department  Salary
0    Arun   21         IT   45000
1    Bala   22         HR   35000
2  Charan   20         IT   50000
3   Divya   23      Sales   42000
4    Esha   21         HR   37000

In [92]:
#Create a new column Bonus = Salary * 0.10.

df["Bonus"] = (df["Salary"] * 0.10)
df.assign(Bonus = df["Salary"] * 0.10)
df

     Name  Age Department  Salary   Bonus
0    Arun   21         IT   45000  4500.0
1    Bala   22         HR   35000  3500.0
2  Charan   20         IT   50000  5000.0
3   Divya   23      Sales   42000  4200.0
4    Esha   21         HR   37000  3700.0

# Level 6 (Missing Values)

In [146]:
data = {
    "Name":["A","B","C","D","E"],
    "Age":[20,None,21,22,None],
    "Salary":[30000,35000,None,45000,50000]
}

df = pd.DataFrame(data)

In [138]:
#Find missing values.

df.isna()
df.isna().any().any()

np.False_

In [104]:
#Count missing values.

df.isna().sum()

Name      0
Age       2
Salary    1
dtype: int64

In [106]:
#Drop rows with missing values.

df.dropna()

  Name   Age   Salary
0    A  20.0  30000.0
3    D  22.0  45000.0

In [136]:
#Fill missing age with average age.
avg_age = df["Age"].mean()
df["Age"]=df["Age"].fillna(avg_age)
df

  Name   Age   Salary
0    A  20.0  30000.0
1    B  21.0  35000.0
2    C  21.0      NaN
3    D  22.0  45000.0
4    E  21.0  50000.0

In [137]:
#Fill missing salary with median salary.
avg_salary = df["Salary"].median()
df["Salary"]=df["Salary"].fillna(avg_salary)
df

  Name   Age   Salary
0    A  20.0  30000.0
1    B  21.0  35000.0
2    C  21.0  40000.0
3    D  22.0  45000.0
4    E  21.0  50000.0

In [124]:
#Replace all missing values with 0.

df.fillna(0)

  Name   Age   Salary
0    A  20.0  30000.0
1    B  21.0  35000.0
2    C  21.0  40000.0
3    D  22.0  45000.0
4    E  21.0  50000.0

In [140]:
#Check if dataframe has any missing value.

df.isna().values.any()

np.False_

In [143]:
#Find percentage of missing values in each column.

(df.isna().sum()/len(df))*100
df.isna().mean() * 100

Name      0.0
Age       0.0
Salary    0.0
dtype: float64

In [147]:
#Drop columns having missing values.

df.dropna(axis=1) # 0 means rows,1 means columns

  Name
0    A
1    B
2    C
3    D
4    E

In [148]:
#Drop columns having missing values.

df.dropna(axis=0) # 0 means rows,1 means columns

  Name   Age   Salary
0    A  20.0  30000.0
3    D  22.0  45000.0

In [150]:
df

  Name   Age   Salary
0    A  20.0  30000.0
1    B   NaN  35000.0
2    C  21.0      NaN
3    D  22.0  45000.0
4    E   NaN  50000.0

In [151]:
#Fill missing values using forward fill.

df.ffill().bfill()

  Name   Age   Salary
0    A  20.0  30000.0
1    B  20.0  35000.0
2    C  21.0  35000.0
3    D  22.0  45000.0
4    E  22.0  50000.0

# ⭐ Challenge Problems

In [156]:
# Find top 3 highest-paid employees.

df.nlargest(3,"Salary")
df.sort_values(by="Salary",ascending=False).head(3)

  Name   Age   Salary
4    E   NaN  50000.0
3    D  22.0  45000.0
1    B   NaN  35000.0

In [168]:
#Find second highest salary.

df.sort_values(by="Salary",ascending=False).iloc[1]
df["Salary"].nlargest(2).iloc[-1]

np.float64(45000.0)